openapi: 3.1.0
info:
  title: Restaurant Reservation Manager API
  version: 0.0.1
servers:
  - url: 'http://localhost:9000/firebase'
    description: local
components:
  responses:
    Error:
      description: An error has occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorSchema'
  schemas:
    ErrorSchema:
      required:
        - errorCode
      properties:
        errorCode:
          type: string

paths:
  /create-user:
    post:
      tags: [ Signup ]
      summary: Create user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: test@user.org 
                password:
                  type: string
                  example: passcorrect
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                required:
                  - userId
                  - accessToken
                properties:
                  resubmit:
                    type: string 
                    example: qslYszIU3hGkXhnBA042xRHplYd3
                  errorMessage:
                    type: string
                    example: >
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJxc2xZc3pJVTNoR2tYaG5CQTA0M
                      nhSSHBsWWQzIiwiZW1haWwiOiJ0ZXN0QHVzZXIub3JnIiwicGFzc3dvcmQiOiJwYXNzY29ycmV
                      jdCIsImlhdCI6MTY3MjQ5ODIzOH0

        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '429':
          $ref: '#/components/responses/Error'
